name: jackpot
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  font_awesome_flutter: ^10.7.0
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.0
  url_launcher: ^6.1.10
  cupertino_icons: ^1.0.8
  google_sign_in: ^5.4.0
  cloud_firestore: ^5.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
