// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzKoYCa1oPKjeY1-dgy0S1WtClObNKlNw',
    appId: '1:392802939910:web:eee05bfbef094409fbbf87',
    messagingSenderId: '392802939910',
    projectId: 'jackpot2-b5af1',
    authDomain: 'jackpot2-b5af1.firebaseapp.com',
    storageBucket: 'jackpot2-b5af1.firebasestorage.app',
    measurementId: 'G-YKFFK7CZ5M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGDaCibIZDYBOai0DD2JFcoWvdzdULOKc',
    appId: '1:392802939910:android:f40a191e33fd7adcfbbf87',
    messagingSenderId: '392802939910',
    projectId: 'jackpot2-b5af1',
    storageBucket: 'jackpot2-b5af1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABDKWiKR78GokibPQ4gMDE77KT06i6pBc',
    appId: '1:392802939910:ios:77131abf7849f8acfbbf87',
    messagingSenderId: '392802939910',
    projectId: 'jackpot2-b5af1',
    storageBucket: 'jackpot2-b5af1.firebasestorage.app',
    iosBundleId: 'com.example.jackpot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABDKWiKR78GokibPQ4gMDE77KT06i6pBc',
    appId: '1:392802939910:ios:77131abf7849f8acfbbf87',
    messagingSenderId: '392802939910',
    projectId: 'jackpot2-b5af1',
    storageBucket: 'jackpot2-b5af1.firebasestorage.app',
    iosBundleId: 'com.example.jackpot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzKoYCa1oPKjeY1-dgy0S1WtClObNKlNw',
    appId: '1:392802939910:web:8f50cae22088e1c5fbbf87',
    messagingSenderId: '392802939910',
    projectId: 'jackpot2-b5af1',
    authDomain: 'jackpot2-b5af1.firebaseapp.com',
    storageBucket: 'jackpot2-b5af1.firebasestorage.app',
    measurementId: 'G-2GHHP5L6VN',
  );
}
